# Site settings
title: Lisbeth Blog
SEOTitle: 沐雪的博客
header-img: img/post-lisbeth-02.jpg
email: 1623454903@qq.com
description: "Every failure is leading towards success."
keyword: "Lisbeth Blog, 沐雪的博客, wangxueqin, 王雪芹, web前端开发"
url: "http://lisbeth0720.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lisbeth0720/lisbeth0720.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-lisbeth.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     沐雪lisbeth
zhihu_username:     mu-xue-81-98/activities
github_username:    lisbeth0720
facebook_username:  lisbeth
jianshu_username:   6ae0befc341f
#twitter_username:   lisbeth




# Build settings
# from 2019, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统

# Disqus（https://disqus.com/）
# disqus_username: lisbeth

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 81312bd43c7735f47192                     #生成的clientID
  clientSecret: dd23f13f6ab8521b1cad1849213a9b2d71aaa0fc    #生成的clientSecret
  repo: lisbeth0720.github.io    #仓库名称
  owner: lisbeth0720    #github用户名
  admin: lisbeth0720
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: 2015cewangxueqin.club              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Lisbeth",
        href: "http://lisbeth0720.github.io"
    },{
        title: "简书",
        href: "https://www.jianshu.com/u/6ae0befc341f"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
